# Generated by Django 5.0.1 on 2024-01-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_battlefield_user_battlefield_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='battlefield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.battlefield'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='horizontal_index',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='vertical_index',
            field=models.IntegerField(blank=True),
        ),
    ]
