# Generated by Django 5.0.1 on 2024-01-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_ship_battlefield_alter_ship_horizontal_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='horizontal_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='vertical_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
